# Generated by Django 5.1.7 on 2025-03-21 14:19

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product Cost')),
                ('stock', models.IntegerField(verbose_name='Product Stock')),
                ('image', stdimage.models.StdImageField(force_min_size=False, upload_to='product_images', variations={'thumbnail': (200, 200)}, verbose_name='Product Image')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Product Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
